name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install OpenGL
      run: powershell ./install-opengl.ps1
    - name: Tool restore
      run: dotnet tool restore
    - name: Build
      run: dotnet fake run build.fsx -t RunCITests
    - name: Uninstall OpenGL
      run: powershell ./install-opengl.ps1 uninstall
