name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Tool restore
      run: dotnet tool restore
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
    - name: Build
      run: dotnet fake run build.fsx
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
